### PR TITLE
v1.3.1

### LINKED ISSUE #285: Update ruby/setup-ruby action
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/dmreslab/DM-res-lab

### Version of Lab Website Template you are using

1.2.2

### Description

Hi, I used your templete for my research lab homepage. But today, I edited my lab but it gives me following error. I thought I might mistake conducting something, but I did a revert three weeks ago commit. And it gives me same error. I think it is related to ruby version in the github pages and local codes. What should I do? Please solve the issue.

Thanks,
Sang Ho Park
 
Run ruby/setup-ruby@v1.172.0
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
In such a case, you should install Ruby in the $RUNNER_TOOL_CACHE yourself, for example using https://github.com/rbenv/ruby-build
You can take inspiration from this workflow for more details: https://github.com/ruby/ruby-builder/blob/master/.github/workflows/build.yml
$ ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
Once that completes successfully, mark it as complete with:
$ touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
It is your responsibility to ensure installing Ruby like that is not done in parallel.

### LINKED ISSUE #287: Always commit citation cache
The citation process automatically caches network requests (immediately, at a per-request level) and stores them in `_cite/.cache/cache.db`. However, when running the citation process on GitHub Actions, changes to this `.db` file go away after each run unless explicitly kept. If you look at [`update-citations.yaml`](https://github.com/greenelab/lab-website-template/blob/main/.github/workflows/update-citations.yaml), the "commit updated citations" step happens after running the main `cite.py` script. If the cite script fails for any reason (e.g. some sources couldn't be cited), it will skip all the remaining steps of the job, and the work that was actually successful and cached in that workflow run will be lost. As such, we should add a "Commit cache" step immediately after the cite script step, which uses `stefanzweifel/git-auto-commit-action@v5` but only commits `cache.db`, and always runs even if the cite script step fails. Make use of [always()](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#always) and/or [continue-on-error](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error).

### LINKED ISSUE #288: Use better escape filters
#274 incorporates `xml_escape` in a bunch of places, which at least stops special characters from breaking HTML parsing. But we can make it better by using `cgi_escape`, `uri_escape`, `strip_html`, or a custom regex to strip whatever characters are appropriate for the context.

Examples:

- `alt` or `aria-label` attributes should ideally remove all special characters, so that they're not announced by screen readers. `xml_escape` will leave behind HTML entities which are annoying to hear on a screen reader.
- `href` and `src` attributes and CSS `url()` should probably use `uri_escape`.

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #288
Closes #287 
Closes #285

New template version checklist:

- [x] I have updated CITATION and CHANGELOG as appropriate.
- [x] I have updated lab-website-template-docs as appropriate.
- [x] I have checked the testbed as appropriate.

---

- use latest major version of setup-ruby gh-action
- run "commit cache" step if citations step fails so that progress (successful citations) will be saved
- replace xml_escape filter with appropriate escapes for each situation, and slightly modify regex_strip filter to allow some basic punctuation

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Still testing the commit cache step on a personal repo. It doesn't seem to be detecting any change to the cache.

**Comment by vincerubinetti** [comment]
For now, I've just removed the `/.cache` ignoring from `.gitignore`. I've asked a question here: https://github.com/stefanzweifel/git-auto-commit-action/discussions/351

But the very first example block of code I give there is actually a lie. I've never seen the [diskcache package I'm using](https://pypi.org/project/diskcache/) create any file other than `cache.db` in that folder, so it's not really an issue.

**Comment by falquaddoomi** [comment]
FWIW, the problem with your `.gitignore` is that you've ignored the `.cache` folder so Git doesn't process the `!cache.db` directive, since it's at the file level and the folder's already been ignored. You can read more about the behavior here: https://git-scm.com/docs/gitignore, specifically this part regarding the `!` operator:
> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. 

You can make the un-ignore more specific by specifying its parent folder with it, i.e. `!.cache/cache.db`, so that it becomes a path-level directive and can successfully override the ignore of `.cache`.

I think just omitting `.cache` from your gitignore is fine, since as you said you only ever see a file that you actually want included in there, but I thought you might be curious how to fix it for other cases.

**Review by falquaddoomi — APPROVED** [review]
Makes sense to me; nice to see you using specific escape functions for specific cases, as that'll definitely be more robust and require less work when it's time to unescape it.

**Pull request merged**
