### PR TITLE
tweak manubot log level

### LINKED ISSUE #112: Show Manubot citation error
In https://github.com/greenelab/greenelab.com/pull/45, there was an invalid source identifier, but the automatic citation process just said "Manubot could not generate citation". This is obviously unhelpful.

I believe I hid all output from the Manubot process, since it generates a lot of text that would clutter the logs. However, it needs to show whatever helpful message Manubot has when it throws an error.

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #112 

- increase manubot log level to "warning" to show message when an invalid identifier type is used
- force manubot logging to gray color
- rearrange `try` blocks around manubot call for a bit better distinction between errors
- make trueHide/trueShow util funcs just be locally `<script>` scoped (like the other util functions) rather than attached to `window`

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@ajlee21 Could you give this a quick review. You can also pass it off to someone else in the Greene Lab if you'd like.

**Review by ajlee21 — APPROVED** [review]
These changes look good to me.

Just one question: What do these changes mean for the user? So if I input say a non-doi for the "id" tag or a non-png/jpg/svg in the "image" tag, will there be some error text in the github actions?

**Comment by vincerubinetti** [comment]
Yes, basically there will be more helpful text in the GitHub actions log. Putting in an id that [isn't valid](https://github.com/greenelab/lab-website-template/wiki/Citations#sourcesyaml) (doesn't have to be a DOI btw) will now look like this:

image

Manubot doesn't throw an error exit code for a warning, so the code will continue, but the second `try` block will catch the warning because Manubot just returns an empty `[]` response.

---

> or a non-png/jpg/svg in the "image" field

This is a different story. This PR doesn't affect anything but the `id`. 

There's no way to tell if a resource is a valid image file just from the url. A url could have no extension but still be an image. Conversely, [a url could end in `.png` but not be a png](https://github.com/greenelab/ponyo/blob/master/logo.png)! 

To truly validate the `image`, I'd have to add lines to this Python script to actually fetch the image (from the internet, or locally) and check its MIME type. I can create an issue for this if you think it's valuable. There is [a warning about this here](https://github.com/greenelab/lab-website-template/wiki/Tips) (first bullet point).

**Comment by ajlee21** [comment]
The extra text in the log files is great! Thank you for clarifying. 

I mentioned the image tag only because I thought when you said "identifier type" that referred to any tag. I don't think the warning is as necessary in this case because when the user checks the pre-build they should very quickly see that there isn't an image and can look up that documentation if they didn't already.

**Pull request merged**
