### PR TITLE
fix: apply last child style only if not only child

### PR DESCRIPTION
**Pull request by Maruuka**
Apply last child style only if not only child
----

Title looked smaller than expected due to a css bug where both `first-child` and `last-child` were applied.

This fix will only apply subtitle styles if there are more than one child element in `.title` otherwise don't apply 

FOR THE TEMPLATE MAINTAINER(S)

New template version checklist:

- [ ] I have updated CITATION and CHANGELOG as appropriate.
- [ ] I have updated lab-website-template-docs as appropriate.
- [ ] I have checked the testbed as appropriate.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Thanks for this, i'll incorporate this into v1.2.0 coming this week.

At a cursory glance i think in your first change, first child should remain first, not last.

**Comment by Maruuka** [comment]
> Thanks for this, i'll incorporate this into v1.2.0 coming this week.
thanks!
 
> At a cursory glance i think in your first change, first child should remain first, not last.

oh you are right, good catch!  I transferred my local changes incorrectly.
fixed the typo

**Comment by vincerubinetti** [comment]
Do you know if it's possible to change the target of your PR from `main` to the `v1.2.0` branch? The versioning workflow does checks to make sure the changelog and stuff like that has been updated, and that shouldn't be on you to update.

I'm guessing it's not possible to change the target, so you can either open a new PR with the same changes, or I can just copy and paste your changes in my own commit to `v1.2.0` and tag your github user name to credit you for the fix.

**Comment by vincerubinetti** [comment]
Superceded by #244 . Will tag you in that for credit. The better solution ended up being just attaching manual "title" and "subtitle" classes to the spans.

**Pull request closed without merging**
